
#production:
#    adapter: mysql
#    database: enginey_production
#    username: timothyf
#    password: 
#    host: db.fisherfamily.com

# MYSQL
development:
  adapter: postgresql
  database: enginey_development
  username: mike
  password:  
  host: localhost

test:
  adapter: postgresql
  database: enginey_test
  username: mike
  password:  
  host: localhost
  

# POSTGRES
#development:
#  adapter: postgresql
#  database: enginey_development
#  username: postgres
#  password: postgres
#  host: localhost
#  encoding: UTF8

#test:
#  adapter: postgresql
#  database: enginey_test
#  username: postgres
#  password: postgres
#  host: localhost
#  encoding: UTF8


